# Generated by Django 4.0.2 on 2022-02-23 18:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api_app', '0002_alter_userprofile_boss_alter_userprofile_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='start_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
